server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/odds
    username: rivertech
    password: rivertech
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create

openapi:
  server:
    url: http://localhost:${server.port}
    title: Tahsin Furkan Keles Technical Case
    version: 1.0.0