version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/rivertech/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: odds
      POSTGRES_USER: rivertech
      POSTGRES_PASSWORD: rivertech
volumes:
  postgres-data: { }